# fly.toml app configuration file generated for everycolor-bsky on 2023-05-22T17:29:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "everycolor-bsky"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
